routes/web.php
<?php
header('Access-Control-Allow-Origin:  *');
header('Access-Control-Allow-Methods:  POST, GET, OPTIONS, PUT, DELETE');
header('Access-Control-Allow-Headers:  Content-Type, X-Auth-Token, Origin, Authorization');
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
    Route::get('/', function () {
        return view('web.public-index');
    });
    Route::get('/package', function () {
        return view('web.public-payment');
    });
    Route::get('/privacy/policy',function(){
        return view('web.public-policy');
    });
    Route::get('/user/login',function(){
        return view('web.olive.public-login');
    })->name('user_web.login');
     Route::get('/user/register',function(){
        return view('web.olive.public-register');
    })->name('user_web.register');
    Route::post('contact/form','web\MainController@ContactFom')->name('ContactFom');
    Route::post('user/regiser','web\MainController@UserRegister')->name('user.register');
    Route::get('service','web\MainController@service')->name('service');
    Route::get('about','web\MainController@about')->name('about');
    Route::get('login','web\MainController@login')->name('login');
    Route::resource('easy-paisa','web\EasyPaisaController');
    Route::any('api', 'SoapController@server');
    Route::any('client/api','SoapController@clientWebService');
Route::prefix('admin')->group(function () {
	Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
		// Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
		// Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
		Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
		Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');


    Route::group(['middleware' => ['auth:admin']], function () {
    	Route::get('/', 'admins\DashboardController@index')->name('dashboard');
    	Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
        Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
        Route::resource('teacher','admins\TeacherController');
        Route::resource('user','admins\UserController');
        Route::resource('admin','admins\AdminController');
        Route::resource('course','admins\CourseController');
        Route::resource('subject','admins\SubjectController');
        Route::resource('level','admins\LevelController');
        Route::resource('question','admins\QuestionController');
        Route::resource('non-verified','admins\Marketing\NonVerifiedUserController');
        Route::resource('bulk-question-edit','admins\BulkQuestionEditController');
        Route::get('topic/bulk-question-edit/{id}','admins\BulkQuestionEditController@questionGetByTOpic')->name('bulk-question-edit.questionGetByTOpic');

        Route::get('chapter/bulk-question-edit/{id}','admins\BulkQuestionEditController@questionGetByChapter')->name('bulk-question-edit.questionGetByChapter');



        Route::post('questionGetAnswer','admins\BulkQuestionEditController@questionGetAnswer')->name('question.questionGetAnswer');
        Route::post('editQuestionTopic','admins\BulkQuestionEditController@editQuestionTopic')->name('question.editQuestionTopic');

        

        Route::resource('approved-question','admins\ApprovedQuestionController');
        Route::resource('user-question','admins\UserQuestionController');
        Route::resource('chapter','admins\ChapterController');
        Route::post('delete/Topic','admins\ChapterController@deleteTopic')->name('deleteTopic');

        Route::resource('chapters','admins\SubjectChapterController');
        Route::post('chapters/status/change','admins\SubjectChapterController@deleteChapter')->name('deleteChapter');



        Route::resource('topic','admins\SectionTopicController');
        Route::resource('own-question','admins\OwnQuestionController');
        Route::resource('report','admins\ReportController');
        Route::resource('user-package','admins\UserPackageController');
        Route::resource('grade','admins\GradeController');
        Route::resource('difficulty','admins\DifficultyController');
        Route::resource('notification','admins\NotificationController');
        Route::resource('question-remove','admins\QuestionRemoveController');
        Route::resource('question-export','admins\SubjectQuestionExportController');
        Route::resource('question-edit','admins\QuestionEditController');
        Route::resource('notes','admins\NotesController');
        Route::resource('video','admins\ChapterVideoController');
        Route::resource('challenge','admins\Challenge\ChallengeController');
        Route::resource('challenge-question','admins\Challenge\ChallengeQuestionController');

        

        Route::resource('past-paper','admins\Paper\CoursePaperController');
         Route::resource('question-past-paper','admins\Paper\QuestionInPastPaperController');
         Route::get('question-pastpaper/{id}','admins\Paper\QuestionInPastPaperController@PastPaperQuestionstore')->name('pastpaper.PastPaperQuestionstore');
         
         Route::get('question-past-paper-create/{id}','admins\Paper\QuestionInPastPaperController@addPastPaperQuestion')->name('addPastPaperQuestion');

         Route::get('question-challenge-create/{id}','admins\Challenge\ChallengeQuestionController@addChallengeQuestion')->name('addChallengeQuestion');
         Route::post('storeQuestionChallenge','admins\Challenge\ChallengeQuestionController@storeQuestionChallenge')->name('storeQuestionChallenge');



         
        Route::post('storeQuestionPastPaper','admins\Paper\QuestionInPastPaperController@storeQuestionPastPaper')->name('storeQuestionPastPaper');




         


        Route::get('question/approved/report','admins\AdminController@approvedReport')->name('approvedReport');


        Route::get('course/subject/detail','admins\SectionTopicController@courseAddTopic')->name('courseAddTopic');
        Route::get('subject/topic-section/{id}/{topic_id}','admins\SectionTopicController@subjectTopics')->name('subjectTopics');
        Route::post('subject/add/topic/','admins\SectionTopicController@subjectAddTopic')->name('subjectAddTopic');


        /////////////////// ajax call/////////////////////
        Route::post('/updateChapter/{id}','admins\ChapterController@updateChapter')->name('updateChapter');
        Route::post('subject/topics','admins\QuestionController@SubjectHasTopic')->name('SubjectHasTopic');
        Route::post('topic/has/subTopic','admins\QuestionController@TopicHasSubtopic')->name('TopicHasSubtopic');
        Route::post('subject/question','admins\QuestionController@getQuestionBySubject')->name('getQuestionBySubject');

        Route::post('subject/question-edit','admins\QuestionController@getQuestionEditBySubject')->name('getQuestionEditBySubject');


        Route::post('approve/question/ans','admins\QuestionController@approveQuestionAns')->name('approveQuestionAns');
        Route::post('dis-approve/questoin','admins\QuestionController@disApproveQuestion')->name('disApproveQuestion');
        Route::post('approved/question','admins\QuestionController@approvedQuestion')->name('approvedQuestion');
        Route::post('unapprove/question/ans','admins\QuestionController@upApproveQuestionAns')->name('upApproveQuestionAns');
        Route::get('own/question','admins\OwnQuestionController@getOwnQuestion')->name('getOwnQuestion');
        Route::post('user/information','admins\UserPackageController@userInformation')->name('userInformation');
        Route::post('/updateSubject/{id}','admins\SubjectController@updateSubject')->name('updateSubject');
        Route::get('question/get/subject/{id}','admins\ApprovedQuestionController@questionget')->name('questionget');

        Route::get('question-edit/get/subject/{id}','admins\QuestionEditController@questionEditget')->name('questionEditget');
        Route::POST('question/delete','admins\QuestionRemoveController@deleteQuestion')->name('deleteQuestion');


        // AJAX Question
        Route::get('questionEditModel/{id}','Ajax\CommonFirstAjaxController@questionEditModel')->name('questionEditModel');
        Route::post('ChapterHasTopic','Ajax\CommonFirstAjaxController@ChapterHasTopic')->name('ChapterHasTopic');
        Route::post('SubjectChapter','Ajax\CommonFirstAjaxController@SubjectChapter')->name('SubjectChapter');
        Route::post('questionUpdateAjax','Ajax\CommonFirstAjaxController@questionUpdateAjax')->name('questionUpdateAjax');


         Route::get('PastPaperQuestionEditModel/{id}','Ajax\AjaxPastPaperController@questionEditModel')->name('PastPaperQuestionEditModel');


        

        




    });

});
    Route::prefix('user')->group(function () {

        Route::post('submit/login','Auth\UserLoginController@login')->name('user.submitLogin');
        Route::post('submit/register','Auth\UserLoginController@register')->name('user.submitRegister');
        Route::get('logout','Auth\UserLoginController@logout')->name('user.logout');
        Route::get('verify/email/{id}','Auth\UserLoginController@confirmEmail')->name('user.confirmEmail');
        

        Route::post('password/request/email', 'Auth\UserFortgotPasswordController@token_create')->name('user.create_token');
        Route::get('/password/reset/{token}', 'Auth\UserFortgotPasswordController@showResetForm')->name('user.password.reset');

app/Http/Controllers/admins/BulkQuestionEditController.php
<?php

namespace App\Http\Controllers\admins;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\BulkQuestionEditRequest;
use App\Models\Question;
use Auth;
use App\Models\Answer;
use App\Models\Chapter;

use App\Models\Topic;
use App\Models\Subject;
use App\Models\Section;
use App\Models\Grade;
use App\Models\Difficulty;
use Session;
class BulkQuestionEditController extends Controller
{
    public function index()
    {
        $topic=Topic::all();
        $subject=Subject::all();
    
        return view('admin.BulkquestionEdit.index',compact('subject','topic'));
    }


    public function store(Request $request){
    	// dd($request->all());

    	$topics=Topic::with('TopicQuestion')->where('sub_id',$request->sub_id)->get();

    	return view('admin.BulkquestionEdit.topic',compact('topics'));
    }

    public function questionGetByTOpic($id){
    	$questions=Question::where('topic_id',$id)->limit(50)->get();
    	$topic=Topic::all();
    	$subject=Subject::all();
        $grade=Grade::all();
        $difficulty=Difficulty::all();
    	return view('admin.BulkquestionEdit.questions',compact('questions','topic','subject','grade','difficulty'));

    }



    public function questionGetByChapter($id){
        $questions=Question::where('chapter_id',$id)->limit(50)->get();
        $topic=Topic::all();
        $subject=Subject::all();
        $grade=Grade::all();
        $difficulty=Difficulty::all();
        return view('admin.BulkquestionEdit.questions',compact('questions','topic','subject','grade','difficulty'));
    }

    public function questionGetAnswer(Request $request){

    	$question=Question::where('id',$request->question_id)->with('answers')->first();
    	// return $question;
    	if(count($question->answers)){
    		return response()->json(['status'=>1,'data'=>$question->answers]);
    	}else{
    		return response()->json(['status'=>0]);
    	}
    }

    public function editQuestionTopic(BulkQuestionEditRequest $request){
    	// dd($request->all());

    	foreach ($request->question_ids as $id) {

    		$question=Question::find($id);
    		if($question){
    			$question->topic_id=$request->topic_id;
    			$question->sub_id=$request->sub_id;
    			$question->grade_id=$request->grade_id;
    			$question->chapter_id=$request->chapter_id;
    			$question->sub_topic_id=$request->sub_topic_id;
    			$question->dif_id=$request->dif_id;
    			$question->save();
    		}
    	}

    	session()->flash('success_message', __('Record update successfully'));
    	return redirect()->back();
    }
}

resources/views/admin/BulkquestionEdit/index.blade.php
<?php
/**
 * Project: Lahore Motor Way City.
 * User: shafqat bhatti
 * Date: 12/03/2019
 * Time: 1:44 PM
 */
?>

@extends('_layouts.admin.default')
@section('title', ' Question Edit')
@section('content')
<section role="main" class="content-body">
  <style>
    .tpic-tstname{
      float: left;
    }
    .tpic-tstname h3{
      margin-top: 0px;
    }
    .tptst-col-left {
      width: 100%;
      background: #fdfdfd;
      /* border: 1px solid; */
      padding: 4px;
      border-left: 4px solid #08c;
      box-shadow: 1px 0px 4px #444;
    }
    .btn-taketest{
      float: right;
    }
  </style>
  <header class="page-header">
    <h2>Manage  Question Edit</h2>
    <div class="right-wrapper pull-right">
      <ol class="breadcrumbs">
        <li>
          <a href="index.html">
            <i class="fa fa-home"></i>
          </a>
        </li>
        <li><span>Index</span></li>
      </ol>
      <a class="sidebar-right-toggle" ></a>
    </div>
  </header>
  <section class="panel">
    <header class="panel-heading">
      <h2 class="panel-title">Manage  Question Edit</h2>
    </header>
    <div class="panel-body">
      <div class="row">

        <div class="panel panel-primary basic_info_panel">
          <div class="panel-heading" style="padding: 20px 0px;background-color:#0088cc;margin-bottom: 20px;box-shadow: 0px 4px 15px dimgrey;"><h4 style="width: 100%;margin-left: 10px;"> <i class="fa fa-user" style="color: #fff;"> </i> <b style="color: #fff!important;
          text-transform: uppercase;"> Question Edit Info</b></h4></div>
          @component('_components.alerts-default')
          @endcomponent
<form method="POST" action="{{route('bulk-question-edit.store')}}">
  @csrf
          <div class="panel-body">
            <div class="row">
              <div class="col-md-9" style="margin-bottom: 20px;">
                <div class="row" style="margin: 10px 0px;">
                  <div class="col-md-12">
                   <label class="control-label">Subject Name</label>
                   <select name="sub_id"  type="text"  class="form-control sub_id" onchange="selectTopic(this)">
                    <option disabled="disabled" selected="selected">Choose the subject</option>
                    @foreach($subject as $sub)
                    <option value="{{$sub->id}}" @if($sub->id==Session()->get('sub_id')) selected @endif>{{$sub->sb_name}}</option>
                    @endforeach
                  </select>
                  @if ($errors->has('name'))
                  <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">×</span>
                      <span class="sr-only">Close</span>
                    </button>
                    <strong>Warning!</strong> {{$errors->first('name')}}
                  </div>
                  @endif
                </div>
                
              </div> 
            </div> 

             
           </div>
           <div class="form-actions">
              <div class="row">
                <div class="col-md-offset-3 col-md-9">

                 <button class="btn btn-success" type="Submit" name="">Save</button>
                     </form>
              <a href="{{route('teacher.index')}}" class="btn  btn-primary" type="reset">Cancel</a>
                  
                  </div>
                </div>
              </div>
         </div>
       </div>

     </div>

   </div>
 </div>
</div>
</section>
</section>
<style type="text/css">
  img{
    width: 100px,
    height:100px;

  }
</style>
@endsection
@push('post-styles')

@endpush
@push('post-scripts')

@endpush

resources/views/admin/BulkquestionEdit/questions.blade.php
<?php
/**
 * Project: Lahore Motor Way City.
 * User: shafqat bhatti
 * Date: 12/03/2019
 * Time: 1:44 PM
 */
?>

@extends('_layouts.admin.default')
@section('title', 'Question Bulk Edit')
@section('content')

<section role="main" class="content-body">
	<header class="page-header">
		<h2>Manage Question Bulk Edit</h2>
		<div class="right-wrapper pull-right">
			<ol class="breadcrumbs">
				<li>
					<a href="{{url('admin')}}">
						<i class="fa fa-home"></i>
					</a>
				</li>
				<li><span>Index</span></li>
			</ol>
			<a class="sidebar-right-toggle" ></a>
		</div>
	</header>
	<section class="panel">
		<header class="panel-heading">
			<h2 class="panel-title">Manage Question Bulk Edit</h2>
		</header>
		<div class="panel-body">
			<div class="row">
				<form method="POST" action="{{route('question.editQuestionTopic')}}">
					@csrf
					<div class="col-md-9" style="margin-bottom: 20px;">
						<div class="row" style="margin: 10px 0px;">

							<div class="col-md-4">
								<label class="control-label">Subject Name</label>
								<select name="sub_id" id="sub_id"  required  type="text"  class="form-control sub_id" >
									<option disabled="disabled" selected="selected">Choose the subject</option>
									@foreach($subject as $sub)
									<option value="{{$sub->id}}" >{{$sub->sb_name}}</option>
									@endforeach
								</select>
								@if ($errors->has('name'))
								<div class="alert alert-danger" role="alert">
									<button type="button" class="close" data-dismiss="alert" aria-label="Close">
										<span aria-hidden="true">×</span>
										<span class="sr-only">Close</span>
									</button>
									<strong>Warning!</strong> {{$errors->first('name')}}
								</div>
								@endif
							</div>
							<div class="col-md-4">
								<label class="control-label"> Grade Name</label>
								<select name="grade_id" id="grade_id" value="{{ old('grade_id') }}" type="text" placeholder="Grade Name" class="form-control grade_id" required>
									<option  selected="selected" value="0">All Grade</option>
									@foreach($grade as $to)
									<option value="{{$to->id}}" >{{$to->grade_name}}</option>
									@endforeach
								</select>

							</div>
							<div class="col-md-4">
								<label class="control-label"> Chapter</label>
								<select name="chapter_id" id="chapter_id" value="{{ old('chapter_id') }}" type="text" class="form-control chapter_id" required>


								

								</select>

							</div>



						</div>
						<div class="row" style="margin: 10px 0px;">
							<div class="col-md-4">
								<label class="control-label"> Topic Name</label>
								<select name="topic_id" id="topic_id" value="{{ old('topic_id') }}" onchange="selectSubTopic(this)" type="text" placeholder="First Name" class="form-control">


								</select>

							</div>
							<div class="col-md-4">
								<label class="control-label"> Sub Topic Name</label >
									<select name="sub_topic_id" id="sub_topic_id" value="{{ old('sub_topic_id') }}" type="text" placeholder="First Name" class="form-control sub_topic_id">
									</select>
								</div>
								<div class="col-md-4">
									<label class="control-label"> Difficulty Level</label>
									<select name="dif_id" value="{{ old('dif_id') }}" type="text" placeholder="First Name" class="form-control dif_id" required>
										<option  selected="selected" value="0">All Difficulty</option>
										@foreach($difficulty as $tops)
										<option value="{{$tops->id}}" >{{$tops->difficulty}}</option>
										@endforeach
									</select>

								</div>
							</div>

							@component('_components.alerts-default')
							@endcomponent
							<h2>Select question for edit</h2>
							<table id="questionTable" class="table table-bordered table-striped mb-none">
								@php($index=1)
								@foreach($questions as $q)
								<tr class="{{$q->id}}"  style="margin-bottom: 15px" for="checkedInput_$q->id">



									<td >
										<div class="row answerApproved{{$q->id}}">
											<div class="" style="margin-bottom: 20px;max-width: 1024px;">
												<div class="row" style="margin: 10px 0px;">
													<div class="col-md-4">
														<label class="control-label">Subject Name</label> 
														<input   type="text"  class="form-control" readonly="" value="@isset($q->subject->sb_name){{$q->subject->sb_name}} @endisset" >

													</div>
													<div class="col-md-4">
														<label class="control-label"> Grade Name</label>
														<input   type="text"  class="form-control" readonly="" value="@isset($q->course->grade_name){{$q->course->grade_name}} @endisset" >

													</div>
													<div class="col-md-4">
														<label class="control-label"> Chapter Name</label>
														<input   type="text"  class="form-control " readonly="" value="@isset($q->chapter->chaper_name){{$q->chapter->chaper_name}} @endisset" >
													</div>


													<div class="col-md-4">
														<label class="control-label"> Topic Name</label>
														<input   type="text"  class="form-control" readonly="" value="@isset($q->topic->name){{$q->topic->name}} @endisset" >


													</div>

													<div class="col-md-4">
														<label class="control-label"> Sub Topic Name</label>
														<input   type="text"  class="form-control" readonly="" value="@isset($q->SubTopic->sub_topic_name){{$q->SubTopic->sub_topic_name}} @endisset" >
													</div>

													<div class="col-md-4">
														<label class="control-label"> Difficulty Level</label>

														<input   type="text"  class="form-control" readonly="" value="@isset($q->difficulty->difficulty){{$q->difficulty->difficulty}} @endisset" >


													</div>

												</div>
											</div> 
										</div> 

										<div>
											<label class="mt-checkbox mt-checkbox-single mt-checkbox-outline"> <input name="question_ids[]"   type="checkbox" class="checkboxes custom-check  checkedInput_$q->id" id="checkedInput_$q->id" value="{{$q->id}}" />  <span></span></label>
											<strong>Question {{$index}}:</strong> {!! $q->question !!} </h4>

											<div><a class="btn btn-warning" href="javascript:;" onclick="getAnswer({{$q->id}})">Answers</a></div>
											<div class="question_answer_{{$q->id}}">

											</div>
										</div>




									</td>
								</tr>
							</form>
							@php($index++)
							@endforeach



						</table>
					</div>
					<div class="row">
						<button type="submit" class="btn btn-success">Update</button>
					</div>
				</form>
			</div>
		</section>


		@endsection

		@push('post-styles')
		<link href="{{asset('assets/bootstrap-datatable/css/dataTables.bootstrap4.min.css')}}" rel="stylesheet" type="text/css">
		<link href="{{asset('assets/bootstrap-datatable/css/buttons.bootstrap4.min.css')}}" rel="stylesheet" type="text/css">
		@endpush

		@push('post-scripts')
		<script src="{{asset('assets/bootstrap-datatable/js/jquery.dataTables.min.js')}}"></script>
		<script src="{{asset('assets/bootstrap-datatable/js/dataTables.bootstrap4.min.js')}}"></script>
		<script src="{{asset('assets/bootstrap-datatable/js/dataTables.buttons.min.js')}}"></script>
		<script src="{{asset('assets/bootstrap-datatable/js/buttons.bootstrap4.min.js')}}"></script>
		<script src="{{asset('assets/bootstrap-datatable/js/jszip.min.js')}}"></script>
		<script src="{{asset('assets/bootstrap-datatable/js/pdfmake.min.js')}}"></script>
		<script src="{{asset('assets/bootstrap-datatable/js/vfs_fonts.js')}}"></script>
		<script src="{{asset('assets/bootstrap-datatable/js/buttons.html5.min.js')}}"></script>
		<script src="{{asset('assets/bootstrap-datatable/js/buttons.print.min.js')}}"></script>
		<script src="{{asset('assets/bootstrap-datatable/js/buttons.colVis.min.js')}}"></script>
		<link href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css" rel="stylesheet">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js"></script>

		<script type="text/javascript">


			var old_topic_id;
			var old_chapter_id;
			var old_sub_topic_id;

			function  getAnswer(obj){
				$.ajax({
					method:"POST",
					url:"{{route('question.questionGetAnswer')}}",
					data : {question_id:obj},
					dataType:"json",
					success:function(res){
						var option=``;
						if(res.status){
							res.data.forEach(function(val,ind){
								var id = val.id;
								var name = val.ans;
								 option += `<p>${name}</p>`;
							});

							$('.question_answer_'+obj).html(option);
						}

					}
				});

			}

			$("[name='sub_id']").add("[name='grade_id']").on('on change',function() {
				SelectChapter();
			});

			$("[name='sub_id']").add("[name='grade_id']").add("[name='chapter_id']").on('on change',function() {
				SelectTopic();
			});

			function SelectChapter(obj){
				console.log(obj);
				$("[name='chapter_id']").html(` <option selected="selected" disabled='disabled' value="0"> Select Chapter  </option>`);
				var sub_id  = $("#sub_id").val();
				var grade_id  = $("#grade_id").val();

				$.ajax({
					method:"POST",
					url:"{{route('SubjectChapter')}}",
					data : {sub_id:sub_id,grade_id:grade_id},
					dataType:"json",
					success:function(res){
						if(res.status){
							res.data.forEach(function(val,ind){
								var id = val.id;
								var name = val.chaper_name;
								var option = `<option value="${id}" ${id==old_chapter_id?'selected':''}>${name}</option>`;
								$("[name='chapter_id']").append(option);
							});


						}

					}
				});
			}

			function SelectTopic(){
				$("[name='topic_id']").html(` <option selected="selected" disabled='disabled' value="0"> Select Topic  </option>`);
				var sub_id  = $("#sub_id").val();
				var grade_id  = $("#grade_id").val();
				var chapter_id  = $("#chapter_id").val();

				$.ajax({
					method:"POST",
					url:"{{route('ChapterHasTopic')}}",
					data : {sub_id:sub_id,grade_id:grade_id,chapter_id:chapter_id},
					dataType:"json",
					success:function(res){
						console.log('old_topic_id',old_topic_id);
						if(res.status){
							res.data.forEach(function(val,ind){
								var id = val.id;
								var name = val.name;
								var option = `<option value="${id}" ${id==old_topic_id?'selected':''}>${name}</option>`;
								$("[name='topic_id']").append(option);
							});
						}

					}
				});
			}


			function selectSubTopic(obj){
				$("#sub_topic_id").first().html(` <option value="0" selected='selected' value="0"> Select sub topic  </option>`);
				var topic_id  = $('#topic_id').val();

				console.log('topic change value',topic_id);
				$.ajax({
					method:"POST",
					url:"{{route('TopicHasSubtopic')}}",
					data : {id:topic_id},
					dataType:"json",
					success:function(res){
						console.log('sub topic response',res);
						if(res.status){
							res.data.forEach(function(val,ind){
								var id = val.id;
								var name = val.sub_topic_name;
								var option = `<option value="${id}" ${id==old_sub_topic_id?'selected':''}>${name}</option>`;
								$("#sub_topic_id").append(option);
							});
						}
						
					}
				});

			}



			$(function(){
				var sub_id=$('.sub_id').val();
				selectTopic();
				var sub_id=$('.sub_id').val();
				var topic_id=$('.sub_id').attr('data-topic_id');


				SelectChapter();
				SelectTopic();
				selectSubTopic(topic_id);
			})


		</script>
		@endpush