routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
    Route::get('/', function () {
        return view('web.public-index');
    });
    Route::get('/package', function () {
        return view('web.public-payment');
    });
    Route::get('/privacy/policy',function(){
        return view('web.public-policy');
    });
    Route::get('/user/login',function(){
        return view('web.olive.public-login');
    })->name('user_web.login');
     Route::get('/user/register',function(){
        return view('web.olive.public-register');
    })->name('user_web.register');
    Route::post('contact/form','web\MainController@ContactFom')->name('ContactFom');
    Route::post('user/regiser','web\MainController@UserRegister')->name('user.register');
    Route::get('service','web\MainController@service')->name('service');
    Route::get('about','web\MainController@about')->name('about');
    Route::get('login','web\MainController@login')->name('login');
    Route::resource('easy-paisa','web\EasyPaisaController');
    Route::any('api', 'SoapController@server');
    Route::any('client/api','SoapController@clientWebService');
Route::prefix('admin')->group(function () {
	Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
		// Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
		// Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
		Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
		Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');


    Route::group(['middleware' => ['auth:admin']], function () {
    	Route::get('/', 'admins\DashboardController@index')->name('dashboard');
    	Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
        Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
        Route::resource('teacher','admins\TeacherController');
        Route::resource('user','admins\UserController');
        Route::resource('admin','admins\AdminController');
        Route::resource('course','admins\CourseController');
        Route::resource('subject','admins\SubjectController');
        Route::resource('level','admins\LevelController');
        Route::resource('question','admins\QuestionController');
        Route::resource('non-verified','admins\Marketing\NonVerifiedUserController');
        Route::resource('bulk-question-edit','admins\BulkQuestionEditController');
        Route::get('topic/bulk-question-edit/{id}','admins\BulkQuestionEditController@questionGetByTOpic')->name('bulk-question-edit.questionGetByTOpic');

        Route::get('chapter/bulk-question-edit/{id}','admins\BulkQuestionEditController@questionGetByChapter')->name('bulk-question-edit.questionGetByChapter');



        Route::post('questionGetAnswer','admins\BulkQuestionEditController@questionGetAnswer')->name('question.questionGetAnswer');
        Route::post('editQuestionTopic','admins\BulkQuestionEditController@editQuestionTopic')->name('question.editQuestionTopic');

        

        Route::resource('approved-question','admins\ApprovedQuestionController');
        Route::resource('user-question','admins\UserQuestionController');
        Route::resource('chapter','admins\ChapterController');
        Route::post('delete/Topic','admins\ChapterController@deleteTopic')->name('deleteTopic');

        Route::resource('chapters','admins\SubjectChapterController');
        Route::post('chapters/status/change','admins\SubjectChapterController@deleteChapter')->name('deleteChapter');



        Route::resource('topic','admins\SectionTopicController');
        Route::resource('own-question','admins\OwnQuestionController');
        Route::resource('report','admins\ReportController');
        Route::resource('user-package','admins\UserPackageController');
        Route::resource('grade','admins\GradeController');
        Route::resource('difficulty','admins\DifficultyController');
        Route::resource('notification','admins\NotificationController');
        Route::resource('question-remove','admins\QuestionRemoveController');
        Route::resource('question-export','admins\SubjectQuestionExportController');
        Route::resource('question-edit','admins\QuestionEditController');
        Route::resource('notes','admins\NotesController');
        Route::resource('video','admins\ChapterVideoController');
        Route::resource('challenge','admins\Challenge\ChallengeController');
        Route::resource('challenge-question','admins\Challenge\ChallengeQuestionController');

        

        Route::resource('past-paper','admins\Paper\CoursePaperController');
         Route::resource('question-past-paper','admins\Paper\QuestionInPastPaperController');
         Route::get('question-pastpaper/{id}','admins\Paper\QuestionInPastPaperController@PastPaperQuestionstore')->name('pastpaper.PastPaperQuestionstore');
         
         Route::get('question-past-paper-create/{id}','admins\Paper\QuestionInPastPaperController@addPastPaperQuestion')->name('addPastPaperQuestion');

         Route::get('question-challenge-create/{id}','admins\Challenge\ChallengeQuestionController@addChallengeQuestion')->name('addChallengeQuestion');
         Route::post('storeQuestionChallenge','admins\Challenge\ChallengeQuestionController@storeQuestionChallenge')->name('storeQuestionChallenge');



         
        Route::post('storeQuestionPastPaper','admins\Paper\QuestionInPastPaperController@storeQuestionPastPaper')->name('storeQuestionPastPaper');




         


        Route::get('question/approved/report','admins\AdminController@approvedReport')->name('approvedReport');


        Route::get('course/subject/detail','admins\SectionTopicController@courseAddTopic')->name('courseAddTopic');
        Route::get('subject/topic-section/{id}/{topic_id}','admins\SectionTopicController@subjectTopics')->name('subjectTopics');
        Route::post('subject/add/topic/','admins\SectionTopicController@subjectAddTopic')->name('subjectAddTopic');


        /////////////////// ajax call/////////////////////
        Route::post('/updateChapter/{id}','admins\ChapterController@updateChapter')->name('updateChapter');
        Route::post('subject/topics','admins\QuestionController@SubjectHasTopic')->name('SubjectHasTopic');
        Route::post('topic/has/subTopic','admins\QuestionController@TopicHasSubtopic')->name('TopicHasSubtopic');
        Route::post('subject/question','admins\QuestionController@getQuestionBySubject')->name('getQuestionBySubject');

        Route::post('subject/question-edit','admins\QuestionController@getQuestionEditBySubject')->name('getQuestionEditBySubject');


        Route::post('approve/question/ans','admins\QuestionController@approveQuestionAns')->name('approveQuestionAns');
        Route::post('dis-approve/questoin','admins\QuestionController@disApproveQuestion')->name('disApproveQuestion');
        Route::post('approved/question','admins\QuestionController@approvedQuestion')->name('approvedQuestion');
        Route::post('unapprove/question/ans','admins\QuestionController@upApproveQuestionAns')->name('upApproveQuestionAns');
        Route::get('own/question','admins\OwnQuestionController@getOwnQuestion')->name('getOwnQuestion');
        Route::post('user/information','admins\UserPackageController@userInformation')->name('userInformation');
        Route::post('/updateSubject/{id}','admins\SubjectController@updateSubject')->name('updateSubject');
        Route::get('question/get/subject/{id}','admins\ApprovedQuestionController@questionget')->name('questionget');

        Route::get('question-edit/get/subject/{id}','admins\QuestionEditController@questionEditget')->name('questionEditget');
        Route::POST('question/delete','admins\QuestionRemoveController@deleteQuestion')->name('deleteQuestion');


        // AJAX Question
        Route::get('questionEditModel/{id}','Ajax\CommonFirstAjaxController@questionEditModel')->name('questionEditModel');
        Route::post('ChapterHasTopic','Ajax\CommonFirstAjaxController@ChapterHasTopic')->name('ChapterHasTopic');
        Route::post('SubjectChapter','Ajax\CommonFirstAjaxController@SubjectChapter')->name('SubjectChapter');
        Route::post('questionUpdateAjax','Ajax\CommonFirstAjaxController@questionUpdateAjax')->name('questionUpdateAjax');


         Route::get('PastPaperQuestionEditModel/{id}','Ajax\AjaxPastPaperController@questionEditModel')->name('PastPaperQuestionEditModel');


        

        




    });

});
    Route::prefix('user')->group(function () {

        Route::post('submit/login','Auth\UserLoginController@login')->name('user.submitLogin');
        Route::post('submit/register','Auth\UserLoginController@register')->name('user.submitRegister');
        Route::get('logout','Auth\UserLoginController@logout')->name('user.logout');
        Route::get('verify/email/{id}','Auth\UserLoginController@confirmEmail')->name('user.confirmEmail');
        

        Route::post('password/request/email', 'Auth\UserFortgotPasswordController@token_create')->name('user.create_token');
        Route::get('/password/reset/{token}', 'Auth\UserFortgotPasswordController@showResetForm')->name('user.password.reset');
        Route::post('/password/reset', 'Auth\UserFortgotPasswordController@reset')->name('user.reset');

         Route::group(['middleware' => ['auth:web']], function () {

                Route::get('/','Users\DashboardController@index')->name('user.dashboard');
                Route::get('/test','Users\DashboardController@testPage')->name('user.test');
                Route::get('success/storey','Users\DashboardController@success_story')->name('success_story');

resources/views/admin/approved/edit.blade.php
<?php
/**
 * Project: Lahore Motor Way City.
 * User: shafqat bhatti
 * Date: 12/03/2019
 * Time: 1:44 PM
 */
?>
@extends('_layouts.admin.default')
@section('title', 'Teacher Edit')
@section('content')
	<section role="main" class="content-body">
		<header class="page-header">
			<h2>Manage Teacher Edit</h2>
			<div class="right-wrapper pull-right">
				<ol class="breadcrumbs">
					<li>
						<a href="index.html">
							<i class="fa fa-home"></i>
						</a>
					</li>
					<li><span>Index</span></li>
				</ol>
				<a class="sidebar-right-toggle" ></a>
			</div>
		</header>
		<section class="panel">
			<header class="panel-heading">
				<h2 class="panel-title">Manage Teacher Edit</h2>
			</header>
			<div class="panel-body">
				<div class="row">
					<div class="panel panel-primary basic_info_panel">
              <div class="panel-heading" style="padding: 20px 0px;background-color:#0088cc;margin-bottom: 20px;box-shadow: 0px 4px 15px dimgrey;"><h4 style="width: 100%;margin-left: 10px;"> <i class="fa fa-user" style="color: #fff;"> </i> <b style="color: #fff!important;
              text-transform: uppercase;">Basic Info</b></h4></div>
              @component('_components.alerts-default')
        @endcomponent
              <form method="POST" action="{{route('teacher.update',$teacher->id)}}" enctype = "multipart/form-data">
              	@csrf
              	@method('PATCH')
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-3">
                    <div class="fileinput fileinput-new" data-provides="fileinput" >
                      <div class="fileinput-new thumbnail" style="width: 250px; height: 250px;">
                          <img src="@if($teacher->images){{asset('images/teacher/'.$teacher->images)}}@else{{asset('images/no-image.png')}}@endif" id="profile-img-tag" height="250" width = "250">
                        </div>
                      </div>
                      <div class="form-group">
                       <label for="images" class="btn btn-primary" style="position: relative;left: 50px;top: 20px;">Upload Profile</label>
                       <input type="file" id="images" value="{{ old('images') }}" name="images" class="hide" style="opacity: 0;">
                       @if ($errors->has('images'))
                       <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">×</span>
                          <span class="sr-only">Close</span>
                        </button>
                        <strong>Warning!</strong> {{$errors->first('images')}}
                      </div>
                      @endif
                    </div>
                    <!-- cnic image upload here -->
                    <div class="col-md-4">
                      <div class="form-group" style="padding: 0px; ">
                        <div class = "gallery"></div>
                      </div>
                    </div>
                  </div><!--form-group ends-->

                  <div class="col-md-9" style="margin-bottom: 20px;">
                    <div class="row" style="margin: 10px 0px;">

                      <div class="col-md-12">
                       <label class="control-label"> Name</label>
                       <input name="name" value="@isset($teacher->name){{$teacher->name}}@endisset" type="text" placeholder="First Name" class="form-control">
                       @if ($errors->has('name'))
                       <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">×</span>
                          <span class="sr-only">Close</span>
                        </button>
                        <strong>Warning!</strong> {{$errors->first('name')}}
                      </div>
                      @endif
                    </div>

                </div>

                <div class="row" style="margin: 10px 0px;">

                  <div class="col-md-6">
                    <label class="control-label">Email</label>
                    <input name="email" type="email" value="@isset($teacher->email){{$teacher->email}}@endisset" class="form-control" placeholder="abc123@example.com">
                    @if ($errors->has('email'))
                    <div class="alert alert-danger" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                      </button>
                      <strong>Warning!</strong> {{$errors->first('email')}}
                    </div>
                    @endif
                  </div><!--form-group ends-->

                  <div class="col-md-6">
                    <label class="control-label">phone</label>
                     <input type="text" name="phone" value="@isset($teacher->phone){{$teacher->phone}}@endisset" placeholder="Mobile No" class="form-control">

                   @if ($errors->has('phone'))
                   <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">×</span>
                      <span class="sr-only">Close</span>
                    </button>
                    <strong>Warning!</strong> {{$errors->first('phone')}}
                  </div>
                  @endif


                </div><!--form-group ends-->

              </div> 
              <div class="row" style="margin: 10px 0px;">

                  <div class="col-md-6">
                    <label class="control-label">Subject</label>
                    <input name="subject" type="text" value="@isset($teacher->subject){{$teacher->subject}}@endisset" class="form-control" placeholder="subject">
                    @if ($errors->has('subject'))
                    <div class="alert alert-danger" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                      </button>
                      <strong>Warning!</strong> {{$errors->first('subject')}}
                    </div>
                    @endif
                  </div><!--form-group ends-->

                  <div class="col-md-6">
                    <label class="control-label">Score</label>
                     <input type="text" name="phone" value="@isset($teacher->score){{$teacher->score}}@endisset" placeholder="Score" class="form-control">

                   @if ($errors->has('score'))
                   <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">×</span>
                      <span class="sr-only">Close</span>
                    </button>
                    <strong>Warning!</strong> {{$errors->first('score')}}
                  </div>
                  @endif


                </div><!--form-group ends-->

              </div> 


              <div class="row" style="margin: 10px 0px;">

                <div class="col-md-6">
                  <label class="control-label">Password</label>
                  <input type="password" placeholder="******" class="form-control" name="password">
                  @if ($errors->has('password'))
                  <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">×</span>
                      <span class="sr-only">Close</span>
                    </button>
                    <strong>Warning!</strong> {{$errors->first('password')}}
                  </div>
                  @endif
                </div><!--form-group ends-->

                <div class="col-md-6">
                  <label class="control-label">Confirm Password</label>
                  <input name="password_confirmation" type="password" placeholder="******" class="form-control">
                </div><!--form-group ends-->

              </div> 
               

            	</div> 
          	</div>
        </div>

      </div>
      <div class="form-actions">
              <div class="row">
                <div class="col-md-offset-3 col-md-9">

                 <button class="btn btn-success" type="Submit" name="">Save</button>
                     </form>
              <a href="{{route('teacher.index')}}" class="btn  btn-primary" type="reset">Cancel</a>
                  
                  </div>
                </div>
              </div>
            </div>
				</div>
			</div>
		</section>
	</section>
@endsection
@push('post-styles')
			
@endpush
@push('post-scripts')
		<script type="text/javascript">
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#profile-img-tag').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }
  $("#images").change(function(){
    readURL(this);
  }); 

</script>

@endpush

resources/views/admin/approved/question.blade.php
<?php
/**
 * Project: Lahore Motor Way City.
 * User: shafqat bhatti
 * Date: 12/03/2019
 * Time: 1:44 PM
 */
?>

@extends('_layouts.admin.default')
@section('title', 'Question')
@section('content')
  <section role="main" class="content-body">
    <header class="page-header">
      <h2>Manage Question</h2>
      <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
          <li>
            <a href="index.html">
              <i class="fa fa-home"></i>
            </a>
          </li>
          <li><span>Index</span></li>
        </ol>
        <a class="sidebar-right-toggle" ></a>
      </div>
    </header>
    <section class="panel">
      <header class="panel-heading">
        <h2 class="panel-title">Manage Question</h2>
      </header>
      <div class="panel-body">
        <div class="row">
          <div class="panel panel-primary basic_info_panel">
          <div class="panel-heading" style="padding: 20px 0px;background-color:#0088cc;margin-bottom: 20px;box-shadow: 0px 4px 15px dimgrey;"><h4 style="width: 100%;margin-left: 10px;"> <i class="fa fa-user" style="color: #fff;"> </i> <b style="color: #fff!important;
          text-transform: uppercase;">Question Info</b></h4></div>
          @component('_components.alerts-default')
          @endcomponent


          <div class="panel-body">
            
        {{-- ///////////////////////////////// Table Show here in row////////////////// --}}
        <div class="row" >
         <div class="" style="max-width: 1024px;">
           <table id="questionTable" class="table table-bordered table-striped mb-none">
            @php($index=1)
            @foreach($question as $q)
            <tr class="{{$q->id}}"  style="margin-bottom: 15px">


              <form method="POST" action="javascript:;" id="answerApproved{{$q->id}}">
                @csrf
              <input type="hidden" name="id" value="{{$q->id}}">
              <input type="hidden" name="question_id" value="{{$q->id}}">
              <input type="hidden" name="dd" class="selectedTopicId" value="{{$q->topic_id}}">
              <td >
                <div class="row answerApproved{{$q->id}}">
                  <div class="" style="margin-bottom: 20px;max-width: 1024px;">
                    <div class="row" style="margin: 10px 0px;">
                      <div class="col-md-3">
                        <label class="control-label">Subject Name</label>
                    <select name="sub_id"  type="text"  class="form-control sub_id" data-topic_id="{{$q->topic_id}}" onchange="selectTopic(this)">
                        <option value="0"  selected="selected">All</option>
                        @foreach($subject as $sub)
                        <option value="{{$sub->id}}" @if($sub->id==$q->sub_id) selected @endif>{{$sub->sb_name}}</option>
                        @endforeach
                      </select>
                    </div>
                    <div class="col-md-3">
                     <label class="control-label"> Topic Name</label>
                     <select name="topic_id" value="{{ old('topic_id') }}" onchange="selectSubTopic(this)" type="text" placeholder="First Name" class="form-control topic_id">
                     
                    </select>
                  </div>
                  <div class="col-md-2">
                     <label class="control-label"> Sub Topic Name</label>
                     <select name="sub_topic_id" value="{{ old('sub_topic_id') }}" type="text" placeholder="First Name" class="form-control sub_topic_id">
                     
                    </select>
                  </div>
                   <div class="col-md-2">
                     <label class="control-label"> Grade Name</label>
                     <select name="grade_id" value="{{ old('grade_id') }}" type="text" placeholder="Grade Name" class="form-control grade_id">
                       <option  selected="selected" value="0">All Grade</option>
                      @foreach($grade as $to)
                      <option value="{{$to->id}}" >{{$to->grade_name}}</option>
                      @endforeach
                    </select>

                  </div>
                   <div class="col-md-2">
                     <label class="control-label"> Difficulty Level</label>
                     <select name="dif_id" value="{{ old('dif_id') }}" type="text" placeholder="First Name" class="form-control dif_id">
                      <option  selected="selected" value="0">All Difficulty</option>
                      @foreach($difficulty as $tops)
                      <option value="{{$tops->id}}" >{{$tops->difficulty}}</option>
                      @endforeach
                    </select>

                  </div>

                </div>
              </div> 
            </div> 

            <div>
              <strong>Question {{$index}}:</strong> {!! $q->question !!} </h4>
            </div>
            @isset($q->answers)
            @php($ansIndex=1)
            @foreach($q->answers as $answer)
            <div class="answer row" style="padding-bottom:10px;max-width: 1024px;">
              <div class="col-md-2" style="padding: 25px,25px,25px,25px">
                <label>IsCorrect</label>&nbsp;&nbsp;&nbsp;
                <input type="radio" @if($answer->is_correct==1){{'checked'}}@endif  name="{{$q->id}}" value="{{$ansIndex}}">
              </div>
              <div class="col-md-4">
                <h4>{!! $answer->ans !!}</h4><h4></h4>
              </div>
            </div>
            @php($ansIndex++)
            @endforeach
            @endisset
            <div class="answer" style="max-width:1024px;">
         
              <div class="col-md-4">
                <a href="{{route('question.edit',$q->id)}}" class="btn btn-info" >Edit </a>
                <button class="btn btn-success" onclick=approveQuestionAns({{$q->id}})>Approve</button>
                <button class="btn btn-danger" onclick=CancelQuestion({{$q->id}})>Cancel</button>
              </div>
            </div>



          </td>
        </tr>
        </form>
        @php($index++)
        @endforeach



      </table>
    </div>
  </div>
  {{-- /////////////////////////////////////// End Table here ///////////////////////////// --}}
</div>
</div>

</div>

</div>
</div>
</div>
</section>
</section>
@endsection
@push('post-styles')
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" rel="stylesheet">

@endpush
@push('post-scripts')
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.js"></script>
<script type="text/javascript">
  $(function(){
    var sub_id=$('.sub_id').val();
    selectTopic(sub_id);
    var sub_id=$('.sub_id').val();
    var topic_id=$('.sub_id').attr('data-topic_id');

    selectSubTopic(topic_id);
  })

</script>
<script type="text/javascript">


  function selectTopic(obj){
    console.log(obj);
    $("[name='topic_id']").html(` <option value="0" selected='selected'> All  </option>`);
    var branch_id  = $("[name='sub_id']").val();
      var topic_id=$('.sub_id').attr('data-topic_id');
    console.log('branch',$("[name='sub_id']").val());
    console.log('subjectId',branch_id);
    $.ajax({
      method:"POST",
      url:"{{route('SubjectHasTopic')}}",
      data : {id:branch_id},
      dataType:"json",
      success:function(data){
        console.log(data);
        data.forEach(function(val,ind){
          var id = val.id;
          var name = val.name;
          console.log('anwer checked',id==topic_id?'selected':'','id',id,'topic_id',topic_id);
          var option = `<option value="${id}" ${id==topic_id?'selected':''}>${name}</option>`;
          $("[name='topic_id']").append(option);
        });
      }
    });
  }
  function selectSubTopic(obj){
    console.log('topic_id autopick',obj);
    $(".sub_topic_id").first().html(` <option value="0" selected='selected'> All  </option>`);
    var branch_id  = $(obj).val();
    if(branch_id==undefined && branch_id==null){
      branch_id=obj;
    }

    console.log('topic change value',$(obj).val());
    $.ajax({
      method:"POST",
      url:"{{route('TopicHasSubtopic')}}",
      data : {id:branch_id},
      dataType:"json",
      success:function(data){
        console.log('sub topic response',data);
        data.forEach(function(val,ind){
          var id = val.id;
          var name = val.sub_topic_name;
          var option = `<option value="${id}" ${id==obj?'selected':''}>${name}</option>`;
          $(".sub_topic_id").first().append(option);
        });
      }
    });
  }

  $('.type').on('change',function(){
    console.log('changed',$(this).val());
    var type=$(this).val();
    if(type==1){
      $('.inputTextarea').show();
      $('.questionFile').css('display',"none");
    }else{
      $('.inputTextarea').css('display',"none");
      $('.questionFile').show();
    }
  });
</script>
<script type="text/javascript">
  $(document).ready(function() {
    $('#summernote').summernote();
    $('#summernote2').summernote();
    $('#summernote3').summernote();
    $('#summernote4').summernote();
    $('#summernote5').summernote();
  });

  $('.typeD').on('change',function(){
    var answerType=$(this).val();
    console.log('answerD',answerType);
    if(answerType==1){
      $('.answerTextD').show();
      $('.answerFileD').css('display',"none");
    }else{
      $('.answerTextD').css('display',"none");
      $('.answerFileD').show();
    }
  });
  $('.typeC').on('change',function(){
    var answerType=$(this).val();
    console.log('answerc',answerType);
    if(answerType==1){
      $('.answerTextC').show();
      $('.answerFileC').css('display',"none");
    }else{
      $('.answerTextC').css('display',"none");
      $('.answerFileC').show();
    }
  });
  $('.typeB').on('change',function(){
    var answerType=$(this).val();
    console.log('answerB',answerType);
    if(answerType==1){
      $('.answerTextB').show();
      $('.answerFileB').css('display',"none");
    }else{
      $('.answerTextB').css('display',"none");
      $('.answerFileB').show();
    }
  });
  $('.typeA').on('change',function(){
    var answerType=$(this).val();
    console.log('answerA',answerType);
    if(answerType==1){
      $('.answerTextA').show();
      $('.answerFileA').css('display',"none");
    }else{
      $('.answerTextA').css('display',"none");
      $('.answerFileA').show();
    }
  });
function CancelQuestion(id){
    $.ajax({
      method:"POST",
      url:"{{route('disApproveQuestion')}}",
      data : {id:id},
      dataType:"json",
      success:function(data){
        console.log('approved Question Request',data);
        // console.log($('.'+id).html());
        if(data.status){
         $('.'+id).closest('tr').remove();

         swal("Question Approved Successfully", "Oops", "warning");
       }
     }
    });
}
  function approveQuestionAns(id){
      var form = $('#answerApproved'+id)[0]; // You need to use standard javascript object here
      var formData = new FormData(form);
      console.log('formData', formData);
      console.log('form', form);
      var topic_id=$('.answerApproved'+id).find('.topic_id').val();
      console.log('requestion topic',topic_id);
      var sub_id=$('.answerApproved'+id).find('.sub_id').val();
      var grade_id=$('.answerApproved'+id).find('.grade_id').val();
      var sub_id=$('.answerApproved'+id).find('.sub_id').val();
      var sub_topic_id=$('.answerApproved'+id).find('.sub_topic_id').val();
      var dif_id=$('.answerApproved'+id).find('.dif_id').val();

   $.ajax({
    method:"POST",
    url:"{{route('approveQuestionAns')}}",
    data : {id:id,topic_id:topic_id,sub_id:sub_id,grade_id:grade_id,sub_topic_id:sub_topic_id,dif_id:dif_id},
    dataType:"json",
    success:function(data){
      console.log('approved Question Request',data);
      // console.log($('.'+id).html());
      if(data.status){
       $('.'+id).closest('tr').remove();

       swal("Question Approved Successfully", "Well done", "success");
     }
   }
 });

 }
</script>
@endpush