routes/web.php
	Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
		// Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
		// Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
		Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
		Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');


    Route::group(['middleware' => ['auth:admin']], function () {
    	Route::get('/', 'admins\DashboardController@index')->name('dashboard');
    	Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
        Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
        Route::resource('teacher','admins\TeacherController');
        Route::resource('user','admins\UserController');
        Route::resource('admin','admins\AdminController');
        Route::resource('course','admins\CourseController');
        Route::resource('subject','admins\SubjectController');
        Route::resource('level','admins\LevelController');
        Route::resource('question','admins\QuestionController');
        Route::resource('non-verified','admins\Marketing\NonVerifiedUserController');
        Route::resource('bulk-question-edit','admins\BulkQuestionEditController');
        Route::get('topic/bulk-question-edit/{id}','admins\BulkQuestionEditController@questionGetByTOpic')->name('bulk-question-edit.questionGetByTOpic');

        Route::get('chapter/bulk-question-edit/{id}','admins\BulkQuestionEditController@questionGetByChapter')->name('bulk-question-edit.questionGetByChapter');



        Route::post('questionGetAnswer','admins\BulkQuestionEditController@questionGetAnswer')->name('question.questionGetAnswer');
        Route::post('editQuestionTopic','admins\BulkQuestionEditController@editQuestionTopic')->name('question.editQuestionTopic');

        

        Route::resource('approved-question','admins\ApprovedQuestionController');
        Route::resource('user-question','admins\UserQuestionController');
        Route::resource('chapter','admins\ChapterController');
        Route::post('delete/Topic','admins\ChapterController@deleteTopic')->name('deleteTopic');

        Route::resource('chapters','admins\SubjectChapterController');
        Route::post('chapters/status/change','admins\SubjectChapterController@deleteChapter')->name('deleteChapter');



        Route::resource('topic','admins\SectionTopicController');
        Route::resource('own-question','admins\OwnQuestionController');
        Route::resource('report','admins\ReportController');
        Route::resource('user-package','admins\UserPackageController');
        Route::resource('grade','admins\GradeController');
        Route::resource('difficulty','admins\DifficultyController');
        Route::resource('notification','admins\NotificationController');
        Route::resource('question-remove','admins\QuestionRemoveController');
        Route::resource('question-export','admins\SubjectQuestionExportController');
        Route::resource('question-edit','admins\QuestionEditController');
        Route::resource('notes','admins\NotesController');
        Route::resource('video','admins\ChapterVideoController');
        Route::resource('challenge','admins\Challenge\ChallengeController');
        Route::resource('challenge-question','admins\Challenge\ChallengeQuestionController');

        

        Route::resource('past-paper','admins\Paper\CoursePaperController');
         Route::resource('question-past-paper','admins\Paper\QuestionInPastPaperController');
         Route::get('question-pastpaper/{id}','admins\Paper\QuestionInPastPaperController@PastPaperQuestionstore')->name('pastpaper.PastPaperQuestionstore');
         
         Route::get('question-past-paper-create/{id}','admins\Paper\QuestionInPastPaperController@addPastPaperQuestion')->name('addPastPaperQuestion');

         Route::get('question-challenge-create/{id}','admins\Challenge\ChallengeQuestionController@addChallengeQuestion')->name('addChallengeQuestion');
         Route::post('storeQuestionChallenge','admins\Challenge\ChallengeQuestionController@storeQuestionChallenge')->name('storeQuestionChallenge');



         
        Route::post('storeQuestionPastPaper','admins\Paper\QuestionInPastPaperController@storeQuestionPastPaper')->name('storeQuestionPastPaper');




         


        Route::get('question/approved/report','admins\AdminController@approvedReport')->name('approvedReport');


        Route::get('course/subject/detail','admins\SectionTopicController@courseAddTopic')->name('courseAddTopic');
        Route::get('subject/topic-section/{id}/{topic_id}','admins\SectionTopicController@subjectTopics')->name('subjectTopics');
        Route::post('subject/add/topic/','admins\SectionTopicController@subjectAddTopic')->name('subjectAddTopic');


        /////////////////// ajax call/////////////////////
        Route::post('/updateChapter/{id}','admins\ChapterController@updateChapter')->name('updateChapter');
        Route::post('subject/topics','admins\QuestionController@SubjectHasTopic')->name('SubjectHasTopic');
        Route::post('topic/has/subTopic','admins\QuestionController@TopicHasSubtopic')->name('TopicHasSubtopic');
        Route::post('subject/question','admins\QuestionController@getQuestionBySubject')->name('getQuestionBySubject');

        Route::post('subject/question-edit','admins\QuestionController@getQuestionEditBySubject')->name('getQuestionEditBySubject');


        Route::post('approve/question/ans','admins\QuestionController@approveQuestionAns')->name('approveQuestionAns');
        Route::post('dis-approve/questoin','admins\QuestionController@disApproveQuestion')->name('disApproveQuestion');
        Route::post('approved/question','admins\QuestionController@approvedQuestion')->name('approvedQuestion');
        Route::post('unapprove/question/ans','admins\QuestionController@upApproveQuestionAns')->name('upApproveQuestionAns');
        Route::get('own/question','admins\OwnQuestionController@getOwnQuestion')->name('getOwnQuestion');
        Route::post('user/information','admins\UserPackageController@userInformation')->name('userInformation');
        Route::post('/updateSubject/{id}','admins\SubjectController@updateSubject')->name('updateSubject');
        Route::get('question/get/subject/{id}','admins\ApprovedQuestionController@questionget')->name('questionget');

        Route::get('question-edit/get/subject/{id}','admins\QuestionEditController@questionEditget')->name('questionEditget');
        Route::POST('question/delete','admins\QuestionRemoveController@deleteQuestion')->name('deleteQuestion');


        // AJAX Question
        Route::get('questionEditModel/{id}','Ajax\CommonFirstAjaxController@questionEditModel')->name('questionEditModel');
        Route::post('ChapterHasTopic','Ajax\CommonFirstAjaxController@ChapterHasTopic')->name('ChapterHasTopic');
        Route::post('SubjectChapter','Ajax\CommonFirstAjaxController@SubjectChapter')->name('SubjectChapter');
        Route::post('questionUpdateAjax','Ajax\CommonFirstAjaxController@questionUpdateAjax')->name('questionUpdateAjax');


         Route::get('PastPaperQuestionEditModel/{id}','Ajax\AjaxPastPaperController@questionEditModel')->name('PastPaperQuestionEditModel');


        

        




    });

});
    Route::prefix('user')->group(function () {

        Route::post('submit/login','Auth\UserLoginController@login')->name('user.submitLogin');
        Route::post('submit/register','Auth\UserLoginController@register')->name('user.submitRegister');
        Route::get('logout','Auth\UserLoginController@logout')->name('user.logout');
        Route::get('verify/email/{id}','Auth\UserLoginController@confirmEmail')->name('user.confirmEmail');
        

        Route::post('password/request/email', 'Auth\UserFortgotPasswordController@token_create')->name('user.create_token');
        Route::get('/password/reset/{token}', 'Auth\UserFortgotPasswordController@showResetForm')->name('user.password.reset');
        Route::post('/password/reset', 'Auth\UserFortgotPasswordController@reset')->name('user.reset');

         Route::group(['middleware' => ['auth:web']], function () {

                Route::get('/','Users\DashboardController@index')->name('user.dashboard');
                Route::get('/test','Users\DashboardController@testPage')->name('user.test');
                Route::get('success/storey','Users\DashboardController@success_story')->name('success_story');
                Route::get('subject/question/{id}','Users\DashboardController@question')->name('user.question');
                Route::get('/practice','Users\DashboardController@practice')->name('user.practice');
                Route::get('subject/{id}/{course_id}','Users\SubjectTopicController@topicSection')->name('subject.topic');
                Route::post('subject/topic/question','Users\SubjectTopicController@getQuestion')->name('getQuestion');

                Route::get('previous/test','Users\DashboardController@previousTest')->name('previous.test');
                Route::get('fulllength/test','Users\DashboardController@fulllength')->name('fulllength.test');
                Route::get('viewnotes/test','Users\DashboardController@viewnotes')->name('viewnotes.test');
                Route::get('writenotes/test','Users\DashboardController@writenotes')->name('writenotes.test');
                /////////////////// Ajax sub Topic /////////////////
                Route::post('subSection','Users\SubjectTopicController@subSection')->name('subSection');
                Route::post('testQuestion/','Users\UserTestController@testQuestion')->name('testQuestion');
                Route::post('question/book/marked','Users\UserTestController@BookMark')->name('BookMark');

app/Models/Challenge.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Challenge extends Model
{
    protected $guarded=[''];
}

app/Http/Controllers/admins/Challenge/ChallengeController.php
<?php

namespace App\Http\Controllers\admins\Challenge;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\ChallengeRequest;

use App\Models\Course;
use App\Models\Subject; 
use App\Models\Grade;

use App\Models\Challenge;
use App\Models\CoursePaperQuestion;

use App\Models\CoursePaperQuestionAnswer;

use Illuminate\Support\Str;


use Session;
use Auth;
use DB;

class ChallengeController extends Controller
{
    public function index()
	{
		$data=Challenge::orderBy('id','DESC')->get();
		return view('admin.challenge.challenge.index',compact('data'));
	}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    	$courses=Course::get();
    	return view('admin.challenge.challenge.create',compact('courses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ChallengeRequest $request)
    {
    	$newUser=Challenge::create([
    		'course_id' => $request->course_id,
    		'challenge_name' => $request->challenge_name,
            'challenge_price' => $request->challenge_price,
            'reward_challenge' => $request->reward_challenge,
            'challenge_description' => $request->challenge_description,
            
    		'slug'=>Str::slug($request->challenge_name),
    		'challenge_date' => $request->challenge_date,
    		'created_by'=>Auth::user()->id,
    		'updated_by'=>Auth::user()->id,
    	]);

    	if($newUser)
    		session()->flash('success_message', __('Record Inserted Successfully'));
    	else
    		session()->flash('error_message', __('Failed! To Insert Record'));

    	return redirect()->route('challenge.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    	$data = Challenge::find($id);
    	$courses=Course::get();

    	if(!$data){
    		Session::flash('error_message',  __('Failed! Record not found'));
    		return redirect()->back();
    	}
    	return View('admin.challenge.challenge.edit',compact('data','courses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ChallengeRequest $request, $id)
    {
        // dd($request->all());
    	$data = Challenge::find($id);

    	if(!$data){
    		Session::flash('error_message', 'Record not found');
    		return redirect()->back();
    	}
    	
    
    	$newUser=Challenge::where('id',$id)->update([
    		'course_id' => $request->course_id,
            'challenge_name' => $request->challenge_name,
            'challenge_price' => $request->challenge_price,
            'reward_challenge' => $request->reward_challenge,
            'challenge_description' => $request->challenge_description,
            'slug'=>Str::slug($request->challenge_name),
            'challenge_date' => $request->challenge_date,
            'updated_by'=>Auth::user()->id,
    	]);



    	if($newUser)
    		session()->flash('success_message', 'Record update Successfully');
    	else
    		session()->flash('error_message','Failed to update record');
    	return redirect()->route('challenge.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/challenge/challenge/create.blade.php
<?php
/**
 * Project: Lahore Motor Way City.
 * User: shafqat bhatti
 * Date: 12/03/2019
 * Time: 1:44 PM
 */
?>

@extends('_layouts.admin.default')
@section('title', 'Challenge')
@section('content')
<section role="main" class="content-body">
  <header class="page-header">
   <h2>Manage Challenge</h2>
   <div class="right-wrapper pull-right">
    <ol class="breadcrumbs">
     <li>
      <a href="index.html">
       <i class="fa fa-home"></i>
     </a>
   </li>
   <li><span>Index</span></li>
 </ol>
 <a class="sidebar-right-toggle" ></a>
</div>
</header>
<section class="panel">
 <header class="panel-heading">
  <h2 class="panel-title">Manage Challenge</h2>
</header>
<div class="panel-body">
  <div class="row">
   <div class="panel panel-primary basic_info_panel">
    <div class="panel-heading" style="padding: 20px 0px;background-color:#0088cc;margin-bottom: 20px;box-shadow: 0px 4px 15px dimgrey;"><h4 style="width: 100%;margin-left: 10px;"> <i class="fa fa-user" style="color: #fff;"> </i> <b style="color: #fff!important;
    text-transform: uppercase;">Basic Info</b></h4></div>
    @component('_components.alerts-default')
    @endcomponent
    <form method="POST" action="{{route('challenge.store')}}" enctype = "multipart/form-data">
     @csrf
     <div class="panel-body">
      <div class="row">


        <div class="col-md-9" style="margin-bottom: 20px;">
          <div class="row" style="margin: 10px 0px;">

            <div class="col-md-12">
             <label class="control-label">Course Name</label>
             <select name="course_id" id="course_id" type="text"  class="form-control course_id">
              @foreach($courses as $sub)
              <option value="{{$sub->id}}">{{$sub->name}}</option>
              @endforeach
            </select>
            @if ($errors->has('sb_name'))
            <div class="alert alert-danger" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
              </button>
              <strong>Warning!</strong> {{$errors->first('sb_name')}}
            </div>
            @endif
          </div>



          <div class="col-md-12">
           <label class="control-label"> Challenge Name</label>
           <input name="challenge_name" value="{{ old('challenge_name') }}" type="text" placeholder="Challenge Name" class="form-control">
           @if ($errors->has('challenge_name'))
           <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">×</span>
              <span class="sr-only">Close</span>
            </button>
            <strong>Warning!</strong> {{$errors->first('challenge_name')}}
          </div>
          @endif
        </div>


        <div class="col-md-12">
         <label class="control-label"> Challenge Join Price </label>
         <input name="challenge_price" value="{{ old('challenge_price') }}" type="number" min="0" placeholder="0" class="form-control">
         @if ($errors->has('challenge_price'))
          <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">×</span>
              <span class="sr-only">Close</span>
            </button>
            <strong>Warning!</strong> {{$errors->first('challenge_price')}}
          </div>
            @endif
        </div>

        <div class="col-md-12">
         <label class="control-label"> Challenge Date </label>
         <input name="challenge_date" value="{{ now() }}" type="date" min="0" placeholder="0" class="form-control">
         @if ($errors->has('challenge_date'))
          <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">×</span>
              <span class="sr-only">Close</span>
            </button>
            <strong>Warning!</strong> {{$errors->first('challenge_date')}}
          </div>
            @endif
        </div>

        <div class="col-md-12">
         <label class="control-label"> Reward Challenge </label>
         <input name="reward_challenge" value="{{ old('reward_challenge') }}" type="number" min="0" placeholder="0" class="form-control">
         @if ($errors->has('reward_challenge'))
          <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">×</span>
              <span class="sr-only">Close</span>
            </button>
            <strong>Warning!</strong> {{$errors->first('reward_challenge')}}
          </div>
            @endif
        </div>

    </div>
    
    <div class="row">


      
          </div>

          <div class="col-md-12">
            <label class="control-label">Description: <span class="req"></span></label>
            <textarea  class="form-control" name="challenge_description" id="challenge_description" maxlength="150"></textarea>

          </div><!--form-group ends-->
        </div>
      </div>
    </div>
  </div>
</div>

<div class="form-actions">
  <div class="row">
    <div class="col-md-offset-3 col-md-9">

     <button class="btn btn-success" type="Submit" name="">Save</button>
   </form>
   <a href="{{route('subject.index')}}" class="btn  btn-primary" type="reset">Cancel</a>

 </div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
@endsection
@push('post-styles')

@endpush

@push('post-scripts')
<script type="text/javascript">

  function SomeDeleteRowFunction(o) {
    console.log(o);
    $(o).parents('.addChapterName').remove();
    var numItems = $('.addChapterName').length;
    console.log('count',numItems);
    if(numItems==0){
      console.log(numItems,'add More');
      $('.addMore').show();
    }

  }


  $(".addMore").click(function() {
    $("#subjectId").attr('readonly', 'true');
    option = `<div class="addChapterName">
    <div class="col-md-10">
    <label class="control-label">Sub Subject Name</label>

    <input name="sub_subject[]" type="text" placeholder="Sub Subject Name" class="form-control">
    </div>
    <div class="col-md-2" style="padding-top: 25px"> 
    <a class="btn btn-success" onclick="SomeAddRowFunction(this)" href="javascript:void(0)">+</a>
    <a class=" btn btn-danger" onclick="SomeDeleteRowFunction(this)" href="javascript:void(0)">-</a>
    </div>
    </div>`;


    $('.addMoreInput').html(option);
    $('.addMore').css('display', 'none');
  });
  function  SomeAddRowFunction(obj){
    console.log('add more',obj);
    option = `<div class="addChapterName">
    <div class="col-md-10">
    <label class="control-label">Sub Subject Name</label>

    <input name="sub_subject[]" type="text" placeholder="Sub Subject Name" class="form-control">
    </div>
    <div class="col-md-2" style="padding-top: 25px"> 
    <a class="btn btn-success" onclick="SomeAddRowFunction(this)" href="javascript:void(0)">+</a>
    <a class=" btn btn-danger" onclick="SomeDeleteRowFunction(this)" href="javascript:void(0)">-</a>
    </div>
    </div>`;

    console.log('add more data',option);
    $('.addMoreInput').append(option);
  }
</script>



@endpush

resources/views/admin/challenge/challenge/edit.blade.php
<?php
/**
 * Project: Lahore Motor Way City.
 * User: shafqat bhatti
 * Date: 12/03/2019
 * Time: 1:44 PM
 */
?>

@extends('_layouts.admin.default')
@section('title', 'Edit Past Paper')
@section('content')
<section role="main" class="content-body">
  <header class="page-header">
   <h2>Edit Past Paper</h2>
   <div class="right-wrapper pull-right">
    <ol class="breadcrumbs">
     <li>
      <a href="index.html">
       <i class="fa fa-home"></i>
     </a>
   </li>
   <li><span>Index</span></li>
 </ol>
 <a class="sidebar-right-toggle" ></a>
</div>
</header>
<section class="panel">
 <header class="panel-heading">
  <h2 class="panel-title">Edit Past Paper</h2>
</header>
<div class="panel-body">
  <div class="row">
   <div class="panel panel-primary basic_info_panel">
    <div class="panel-heading" style="padding: 20px 0px;background-color:#0088cc;margin-bottom: 20px;box-shadow: 0px 4px 15px dimgrey;"><h4 style="width: 100%;margin-left: 10px;"> <i class="fa fa-user" style="color: #fff;"> </i> <b style="color: #fff!important;
    text-transform: uppercase;">Basic Info</b></h4></div>
    @component('_components.alerts-default')
    @endcomponent
    <form method="POST" action="{{route('past-paper.update',$data->id)}}" enctype = "multipart/form-data">
     @csrf
     @method('PATCH')
     <div class="panel-body">
      <div class="row">


        <div class="col-md-9" style="margin-bottom: 20px;">
          <div class="row" style="margin: 10px 0px;">

            <div class="col-md-12">
             <label class="control-label">Course Name</label>
             <select name="course_id" id="course_id" type="text"  class="form-control course_id">
              @foreach($courses as $sub)
              <option value="{{$sub->id}}" @if($data->course_id==$sub->id) selected @endif>{{$sub->name}}</option>
              @endforeach
            </select>
            @if ($errors->has('sb_name'))
            <div class="alert alert-danger" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
                <span class="sr-only">Close</span>
              </button>
              <strong>Warning!</strong> {{$errors->first('sb_name')}}
            </div>
            @endif
          </div>

          <div class="col-md-12">
           <label class="control-label"> Past Paper Name</label>
           <input name="past_paper_name" value="{{ $data->past_paper_name }}" type="text" placeholder="Past Paper Name" class="form-control">
           @if ($errors->has('past_paper_name'))
           <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">×</span>
              <span class="sr-only">Close</span>
            </button>
            <strong>Warning!</strong> {{$errors->first('past_paper_name')}}
          </div>
          @endif
        </div>


        <div class="col-md-12">
         <label class="control-label"> Year </label>
         <input name="year" value="{{ $data->year}}" type="number" min="0" placeholder="Past Paper Name" class="form-control">
         @if ($errors->has('year'))
         <div class="alert alert-danger" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
            <span class="sr-only">Close</span>
          </button>
          <strong>Warning!</strong> {{$errors->first('year')}}
        </div>
        @endif
      </div>

    </div>
    

  </div>
</div>
</div>
</div>

<div class="form-actions">
  <div class="row">
    <div class="col-md-offset-3 col-md-9">

     <button class="btn btn-success" type="Submit" name="">Save</button>
   </form>

 </div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
@endsection
@push('post-styles')

@endpush

@push('post-scripts')




@endpush

resources/views/admin/challenge/challenge/index.blade.php
<?php
/**
 * Project: Lahore Motor Way City.
 * User: shafqat bhatti
 * Date: 12/03/2019
 * Time: 1:44 PM
 */
?>

@extends('_layouts.admin.default')
@section('title', 'Challenge')
@section('content')

	<section role="main" class="content-body">
		<header class="page-header">
			<h2>Manage Challenge</h2>
			<div class="right-wrapper pull-right">
				<ol class="breadcrumbs">
					<li>
						<a href="{{url('admin')}}">
							<i class="fa fa-home"></i>
						</a>
					</li>
					<li><span>Index</span></li>
				</ol>
				<a class="sidebar-right-toggle" ></a>
			</div>
		</header>
		<section class="panel">
			<header class="panel-heading">
				<h2 class="panel-title">Manage Challenge</h2>
			</header>
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-12">
						<div class="mb-md" style="float:left;">
							<a class="btn btn-primary" href="{{route('challenge.create')}}">Add Challenge &nbsp;<i class="fa fa-plus"></i></a>
						</div>
					</div>
				</div>
			
					@component('_components.alerts-default')
        		@endcomponent
					<table id="example" class="table border table-bordered">
						<thead>
							<tr style=" color: white; background: linear-gradient(#0088cc, #fff) !important; font-weight: unset;">
								<th>#id</th>

								<th>Challenge Name</th>
 								<th>Date</th>
 								<th>Price</th>
 								<th>Reward Price</th>

 								<th>Total Question</th>

								<th>Action</th>
							</tr>
						</thead>
						<tbody>
									@isset($data)
									@foreach($data as $pro)
									<tr>
										<td>@isset($pro->id){{$pro->id}}@endisset</td>
										<td>@isset($pro->challenge_name){{$pro->challenge_name}}@endisset</td>
										<td>@isset($pro->challenge_date){{$pro->challenge_date}}@endisset</td>

										<td>@isset($pro->challenge_price){{$pro->challenge_price}}@endisset</td>

										<td>@isset($pro->reward_challenge){{$pro->reward_challenge}}@endisset</td>



										<td>@isset($pro->status){{$pro->status}}@endisset</td>
										<td><a href="{{route('challenge.edit',$pro->id)}}" class="btn btn-info btn-sm">Edit</a>
											<form method="POST" action="{{route('challenge-question.store')}}">
												@csrf
												<input type="hidden" name="id" value="@isset($pro->id){{$pro->id}}@endisset">
												
												<button type="submit" class="btn btn-success btn-sm">Add Question</button>
											</form>
											
										</td>
									</tr>
									@endforeach
									@endisset
						</tbody>
					</table>
				</div>
			</div>
		</section>


@endsection

@push('post-styles')
	<link href="{{asset('assets/bootstrap-datatable/css/dataTables.bootstrap4.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('assets/bootstrap-datatable/css/buttons.bootstrap4.min.css')}}" rel="stylesheet" type="text/css">
@endpush

@push('post-scripts')
<script src="{{asset('assets/bootstrap-datatable/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/buttons.bootstrap4.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/jszip.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/pdfmake.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/vfs_fonts.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/buttons.html5.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/buttons.print.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/buttons.colVis.min.js')}}"></script>

<script>
	$(document).ready(function() {
     //Default data table
     $('#default-datatable').DataTable();


     var table = $('#example').DataTable( {
     	"order": [[ 0, "desc" ]],
     	lengthChange: false,
     	buttons: [ 'copy', 'excel', 'pdf', 'print', 'colvis' ]
     } );

     table.buttons().container()
     .appendTo( '#example_wrapper .col-md-6:eq(0)' );

 } );
</script>
@endpush