routes/web.php
<?php
header('Access-Control-Allow-Origin:  *');
header('Access-Control-Allow-Methods:  POST, GET, OPTIONS, PUT, DELETE');
header('Access-Control-Allow-Headers:  Content-Type, X-Auth-Token, Origin, Authorization');
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
    Route::get('/', function () {
        return view('web.public-index');
    });
    Route::get('/package', function () {
        return view('web.public-payment');
    });
    Route::get('/privacy/policy',function(){
        return view('web.public-policy');
    });
    Route::get('/user/login',function(){
        return view('web.olive.public-login');
    })->name('user_web.login');
     Route::get('/user/register',function(){
        return view('web.olive.public-register');
    })->name('user_web.register');
    Route::post('contact/form','web\MainController@ContactFom')->name('ContactFom');
    Route::post('user/regiser','web\MainController@UserRegister')->name('user.register');
    Route::get('service','web\MainController@service')->name('service');
    Route::get('about','web\MainController@about')->name('about');
    Route::get('login','web\MainController@login')->name('login');
    Route::resource('easy-paisa','web\EasyPaisaController');
    Route::any('api', 'SoapController@server');
    Route::any('client/api','SoapController@clientWebService');
Route::prefix('admin')->group(function () {
	Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
		// Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
		// Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
		Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
		Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');


    Route::group(['middleware' => ['auth:admin']], function () {
    	Route::get('/', 'admins\DashboardController@index')->name('dashboard');
    	Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
        Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
        Route::resource('teacher','admins\TeacherController');
        Route::resource('user','admins\UserController');
        Route::resource('admin','admins\AdminController');
        Route::resource('course','admins\CourseController');
        Route::resource('subject','admins\SubjectController');
        Route::resource('level','admins\LevelController');
        Route::resource('question','admins\QuestionController');
        Route::resource('non-verified','admins\Marketing\NonVerifiedUserController');
        Route::resource('bulk-question-edit','admins\BulkQuestionEditController');
        Route::get('topic/bulk-question-edit/{id}','admins\BulkQuestionEditController@questionGetByTOpic')->name('bulk-question-edit.questionGetByTOpic');

        Route::get('chapter/bulk-question-edit/{id}','admins\BulkQuestionEditController@questionGetByChapter')->name('bulk-question-edit.questionGetByChapter');



        Route::post('questionGetAnswer','admins\BulkQuestionEditController@questionGetAnswer')->name('question.questionGetAnswer');
        Route::post('editQuestionTopic','admins\BulkQuestionEditController@editQuestionTopic')->name('question.editQuestionTopic');

        

        Route::resource('approved-question','admins\ApprovedQuestionController');
        Route::resource('user-question','admins\UserQuestionController');
        Route::resource('chapter','admins\ChapterController');
        Route::post('delete/Topic','admins\ChapterController@deleteTopic')->name('deleteTopic');

        Route::resource('chapters','admins\SubjectChapterController');
        Route::post('chapters/status/change','admins\SubjectChapterController@deleteChapter')->name('deleteChapter');



        Route::resource('topic','admins\SectionTopicController');
        Route::resource('own-question','admins\OwnQuestionController');
        Route::resource('report','admins\ReportController');
        Route::resource('user-package','admins\UserPackageController');
        Route::resource('grade','admins\GradeController');
        Route::resource('difficulty','admins\DifficultyController');
        Route::resource('notification','admins\NotificationController');
        Route::resource('question-remove','admins\QuestionRemoveController');
        Route::resource('question-export','admins\SubjectQuestionExportController');
        Route::resource('question-edit','admins\QuestionEditController');
        Route::resource('notes','admins\NotesController');
        Route::resource('video','admins\ChapterVideoController');
        Route::resource('challenge','admins\Challenge\ChallengeController');
        Route::resource('challenge-question','admins\Challenge\ChallengeQuestionController');

        

        Route::resource('past-paper','admins\Paper\CoursePaperController');
         Route::resource('question-past-paper','admins\Paper\QuestionInPastPaperController');
         Route::get('question-pastpaper/{id}','admins\Paper\QuestionInPastPaperController@PastPaperQuestionstore')->name('pastpaper.PastPaperQuestionstore');
         
         Route::get('question-past-paper-create/{id}','admins\Paper\QuestionInPastPaperController@addPastPaperQuestion')->name('addPastPaperQuestion');

         Route::get('question-challenge-create/{id}','admins\Challenge\ChallengeQuestionController@addChallengeQuestion')->name('addChallengeQuestion');
         Route::post('storeQuestionChallenge','admins\Challenge\ChallengeQuestionController@storeQuestionChallenge')->name('storeQuestionChallenge');



         
        Route::post('storeQuestionPastPaper','admins\Paper\QuestionInPastPaperController@storeQuestionPastPaper')->name('storeQuestionPastPaper');




         


        Route::get('question/approved/report','admins\AdminController@approvedReport')->name('approvedReport');


        Route::get('course/subject/detail','admins\SectionTopicController@courseAddTopic')->name('courseAddTopic');
        Route::get('subject/topic-section/{id}/{topic_id}','admins\SectionTopicController@subjectTopics')->name('subjectTopics');
        Route::post('subject/add/topic/','admins\SectionTopicController@subjectAddTopic')->name('subjectAddTopic');


        /////////////////// ajax call/////////////////////
        Route::post('/updateChapter/{id}','admins\ChapterController@updateChapter')->name('updateChapter');
        Route::post('subject/topics','admins\QuestionController@SubjectHasTopic')->name('SubjectHasTopic');
        Route::post('topic/has/subTopic','admins\QuestionController@TopicHasSubtopic')->name('TopicHasSubtopic');
        Route::post('subject/question','admins\QuestionController@getQuestionBySubject')->name('getQuestionBySubject');

        Route::post('subject/question-edit','admins\QuestionController@getQuestionEditBySubject')->name('getQuestionEditBySubject');


        Route::post('approve/question/ans','admins\QuestionController@approveQuestionAns')->name('approveQuestionAns');
        Route::post('dis-approve/questoin','admins\QuestionController@disApproveQuestion')->name('disApproveQuestion');
        Route::post('approved/question','admins\QuestionController@approvedQuestion')->name('approvedQuestion');
        Route::post('unapprove/question/ans','admins\QuestionController@upApproveQuestionAns')->name('upApproveQuestionAns');
        Route::get('own/question','admins\OwnQuestionController@getOwnQuestion')->name('getOwnQuestion');
        Route::post('user/information','admins\UserPackageController@userInformation')->name('userInformation');
        Route::post('/updateSubject/{id}','admins\SubjectController@updateSubject')->name('updateSubject');
        Route::get('question/get/subject/{id}','admins\ApprovedQuestionController@questionget')->name('questionget');

        Route::get('question-edit/get/subject/{id}','admins\QuestionEditController@questionEditget')->name('questionEditget');
        Route::POST('question/delete','admins\QuestionRemoveController@deleteQuestion')->name('deleteQuestion');


        // AJAX Question
        Route::get('questionEditModel/{id}','Ajax\CommonFirstAjaxController@questionEditModel')->name('questionEditModel');
        Route::post('ChapterHasTopic','Ajax\CommonFirstAjaxController@ChapterHasTopic')->name('ChapterHasTopic');
        Route::post('SubjectChapter','Ajax\CommonFirstAjaxController@SubjectChapter')->name('SubjectChapter');
        Route::post('questionUpdateAjax','Ajax\CommonFirstAjaxController@questionUpdateAjax')->name('questionUpdateAjax');


         Route::get('PastPaperQuestionEditModel/{id}','Ajax\AjaxPastPaperController@questionEditModel')->name('PastPaperQuestionEditModel');


        

        




    });

});
    Route::prefix('user')->group(function () {

        Route::post('submit/login','Auth\UserLoginController@login')->name('user.submitLogin');
        Route::post('submit/register','Auth\UserLoginController@register')->name('user.submitRegister');
        Route::get('logout','Auth\UserLoginController@logout')->name('user.logout');
        Route::get('verify/email/{id}','Auth\UserLoginController@confirmEmail')->name('user.confirmEmail');
        

        Route::post('password/request/email', 'Auth\UserFortgotPasswordController@token_create')->name('user.create_token');
        Route::get('/password/reset/{token}', 'Auth\UserFortgotPasswordController@showResetForm')->name('user.password.reset');

app/Models/User.php
<?php

namespace App\Models;


use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use DB;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded=[];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token','course_id','province_id','address'
    ];

    public function BillInquiry(){
        return $this->hasOne(UserRequest::class,'user_id')->orderBy('id','DESC');
    }
    public function userPackage(){
        return $this->hasOne(UserHasPacakge::class,'user_id')->orderBy('id','DESC');
    }

   

    

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Users/DashboardController.php
<?php

namespace App\Http\Controllers\Users;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\Subject;
use App\Models\Question;
use App\Models\Topic;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\ApiMessageController;
class DashboardController extends Controller
{
    public function index(){
    	return view('user.dashboard');
    }
    public function testPage(){
    	$course=Course::where('status',1)->with('couseSubject.subject')->get();
    	return view('user.test',compact('course'));
    }
    public function success_story(){
    	return view('user.success_story');
    }
    public function question($id){
    	$question=Question::where('topic_id',$id)->with('answers')->where('hasAns',1)->paginate(12);
        $topic=Topic::find($id);
    	return view('user.questions',compact('question','id','topic'));
    }
    public function practice(){
    	$data=Subject::where('status',1)->with('filterChapters')->get();
    	return view('user.practiceBook',compact('data'));
    }
    public function previousTest(){
        return view("user.previousTest");
    }
  public function fulllength(){
        return view("user.fulllength");
    }
      public function viewnotes(){
        return view("user.viewnotes");
    }
       public function writenotes(){
        return view("user.writenotes");
    }
    public function subjectTopic(Request $request)
    {
        try {
            $allInputs = $request->all();
            $id = $request->input('id');


            $validation = Validator::make($allInputs, [
                'id' => 'required'
            ]);

            if ($validation->fails()) {
                $response = (new ApiMessageController())->validatemessage($validation->errors()->first());
            } else {
            	 $data=Topic::where('sub_id',$id)->where('hasQuestion','>',10)->where('status',1)->get();
                $subject = Subject::find($id);

                return view('user.subjectTopic',compact('data','subject'));
            }
        } catch
        (\Illuminate\Database\QueryException $ex) {
            $response = (new ApiMessageController())->queryexception($ex);
        }
        return $response;
    }
}

app/Http/Controllers/Users/SubjectTopicController.php
<?php

namespace App\Http\Controllers\Users;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\Subject;
use App\Models\Question;
use App\Models\Topic;
use App\Models\CourseSubject;
use App\Models\CourseSubjectTopic;
use App\Models\SubTopic;
use App\Models\Test;
use App\Models\TestDetail;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\ApiMessageController;
use Auth;
class SubjectTopicController extends Controller
{
    public function topicSection($id,$course_id=null){
    	$data=Subject::with('chapters','chapters.subTopic')->find($id);

    	// dd($data);
    	return view('user.sectionSubsection',compact('data','course_id','id'));
    }

    public function subSection(Request $request){
        $student=SubTopic::select('id','sub_topic_name')->where('topic_id',$request->id)->get();
        if(count($student)){

            return response()->json(['data'=>$student,'status'=>1],200);
        }else{
            $message='Record not found';
             return response()->json(['data'=>$message,'status'=>0], 200);
        }
    }
    public function getQuestion(Request $request){
        sessionValueFlush();
        $course= Course::find($request->selected_course_id);
        $subject= Subject::find($request->sub_id);
        $testName=(isset($subject->sb_name)?$subject->sb_name:'').' of '.(isset($course->name)?$course->name:'');

        $test=Test::create([
            'test_name'=>($request->testName)?$request->testName:'',
            'user_id'=>Auth::user()->id,
            'course_id'=>($request->selected_course_id)?$request->selected_course_id:'',
            'sub_id'=>($request->sub_id)?$request->sub_id:'',
            'level'=>($request->level)?$request->level:0,
            'test_date'=>date('Y-m-d'),
            'description'=>($request->description)?$request->description:''
            ]);

        $question=Question::where('sub_id',$request->sub_id)->with('answers');
        if(isset($request->section_id) && count($request->section_id))
            $question->whereIn('topic_id',$request->section_id);

        if(isset($request->sub_section_id) && count($request->sub_section_id))
            $question->whereIn('sub_topic_id',$request->sub_section_id);

         if(isset($request->no_of_question) && !empty($request->no_of_question))
             $question->limit($request->no_of_question);

         $ques=$question->get();
         $testId=$test->id;
    	return view('user.getQuestion',compact('ques','testId'));
    }

    public function testResult(Request $request){
            $result=Test::with('testDetail')->find($request->test_id);
            // return $result->correctQuestionCount();
            $content=view('user.resultAjax',compact('result'))->render();
            return response()->json(['data'=>$content,'status'=>1], 200);

    }
}

resources/views/admin/user/create.blade.php
<?php
/**
 * Project: Lahore Motor Way City.
 * User: shafqat bhatti
 * Date: 12/03/2019
 * Time: 1:44 PM
 */
?>

@extends('_layouts.admin.default')
@section('title', 'User')
@section('content')
	<section role="main" class="content-body">
		<header class="page-header">
			<h2>Manage User</h2>
			<div class="right-wrapper pull-right">
				<ol class="breadcrumbs">
					<li>
						<a href="index.html">
							<i class="fa fa-home"></i>
						</a>
					</li>
					<li><span>Index</span></li>
				</ol>
				<a class="sidebar-right-toggle" ></a>
			</div>
		</header>
		<section class="panel">
			<header class="panel-heading">
				<h2 class="panel-title">Manage User</h2>
			</header>
			<div class="panel-body">
				<div class="row">
					<div class="panel panel-primary basic_info_panel">
              <div class="panel-heading" style="padding: 20px 0px;background-color:#0088cc;margin-bottom: 20px;box-shadow: 0px 4px 15px dimgrey;"><h4 style="width: 100%;margin-left: 10px;"> <i class="fa fa-user" style="color: #fff;"> </i> <b style="color: #fff!important;
              text-transform: uppercase;">Basic Info</b></h4></div>
              @component('_components.alerts-default')
        @endcomponent
              <form method="POST" action="{{route('user.store')}}" enctype = "multipart/form-data">
              	@csrf
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-3">
                    <div class="fileinput fileinput-new" data-provides="fileinput" >
                      <div class="fileinput-new thumbnail" style="width: 250px; height: 250px;">
                          <img src="{{asset('images/no-image.png')}}" id="profile-img-tag" height="250" width = "250">
                        </div>
                      </div>
                      <div class="form-group">
                       <label for="images" class="btn btn-primary" style="position: relative;left: 50px;top: 20px;">Upload Profile</label>
                       <input type="file" id="images" value="{{ old('images') }}" name="images" class="hide" style="opacity: 0;">
                       @if ($errors->has('images'))
                       <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">×</span>
                          <span class="sr-only">Close</span>
                        </button>
                        <strong>Warning!</strong> {{$errors->first('images')}}
                      </div>
                      @endif
                    </div>
                    <!-- cnic image upload here -->
                    <div class="col-md-4">
                      <div class="form-group" style="padding: 0px; ">
                        <div class = "gallery"></div>
                      </div>
                    </div>
                  </div><!--form-group ends-->

                  <div class="col-md-9" style="margin-bottom: 20px;">
                    <div class="row" style="margin: 10px 0px;">

                      <div class="col-md-12">
                       <label class="control-label"> Name</label>
                       <input name="name" value="{{ old('name') }}" type="text" placeholder="First Name" class="form-control">
                       @if ($errors->has('name'))
                       <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">×</span>
                          <span class="sr-only">Close</span>
                        </button>
                        <strong>Warning!</strong> {{$errors->first('name')}}
                      </div>
                      @endif
                    </div>

                </div>

                <div class="row" style="margin: 10px 0px;">
                  <div class="col-md-6">
                    <label class="control-label">Email</label>
                    <input name="email" type="email" value="{{ old('email') }}" class="form-control" placeholder="abc123@example.com">
                    @if ($errors->has('email'))
                    <div class="alert alert-danger" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                      </button>
                      <strong>Warning!</strong> {{$errors->first('email')}}
                    </div>
                    @endif
                  </div><!--form-group ends-->

                  <div class="col-md-6">
                    <label class="control-label">phone</label>
                     <input type="text" name="phone" value="{{ old('phone') }}" placeholder="Mobile No" class="form-control">

                   @if ($errors->has('phone'))
                   <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">×</span>
                      <span class="sr-only">Close</span>
                    </button>
                    <strong>Warning!</strong> {{$errors->first('phone')}}
                  </div>
                  @endif


                </div><!--form-group ends-->

              </div> 
             

              <div class="row" style="margin: 10px 0px;">

                <div class="col-md-6">
                  <label class="control-label">Password</label>
                  <input type="password" placeholder="******" class="form-control" name="password">
                  @if ($errors->has('password'))
                  <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">×</span>
                      <span class="sr-only">Close</span>
                    </button>
                    <strong>Warning!</strong> {{$errors->first('password')}}
                  </div>
                  @endif
                </div><!--form-group ends-->

                <div class="col-md-6">
                  <label class="control-label">Confirm Password</label>
                  <input name="password_confirmation" type="password" placeholder="******" class="form-control">
                </div><!--form-group ends-->

              </div> 
               

            	</div> 
          	</div>
        </div>

      </div>
      <div class="form-actions">
              <div class="row">
                <div class="col-md-offset-3 col-md-9">

                 <button class="btn btn-success" type="Submit" name="">Save</button>
                     </form>
              <a href="{{route('teacher.index')}}" class="btn  btn-primary" type="reset">Cancel</a>
                  
                  </div>
                </div>
              </div>
            </div>
				</div>
			</div>
		</section>
	</section>
@endsection
@push('post-styles')
			
@endpush
@push('post-scripts')
		<script type="text/javascript">
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#profile-img-tag').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }
  $("#images").change(function(){
    readURL(this);
  }); 

</script>

@endpush

resources/views/admin/user/index.blade.php
<?php
/**
 * Project: Lahore Motor Way City.
 * User: shafqat bhatti
 * Date: 12/03/2019
 * Time: 1:44 PM
 */
?>

@extends('_layouts.admin.default')
@section('title', 'User')
@section('content')

	<section role="main" class="content-body">
		<header class="page-header">
			<h2>Manage User</h2>
			<div class="right-wrapper pull-right">
				<ol class="breadcrumbs">
					<li>
						<a href="index.html">
							<i class="fa fa-home"></i>
						</a>
					</li>
					<li><span>Index</span></li>
				</ol>
				<a class="sidebar-right-toggle" ></a>
			</div>
		</header>
		<section class="panel">
			<header class="panel-heading">
				<h2 class="panel-title">Manage User</h2>
			</header>
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-12">
						<div class="mb-md" style="float:left;">
							<a class="btn btn-primary" href="{{route('user.create')}}">Add User &nbsp;<i class="fa fa-plus"></i></a>
						</div>
					</div>
				</div>
			
					@component('_components.alerts-default')
        		@endcomponent
					<table id="" class="table border table-bordered">
						<thead>
							<tr style=" color: white; background: linear-gradient(#0088cc, #fff) !important; font-weight: unset;">
								<th>#id</th>
								<th>Image</th>
								<th>Name</th>
								<th>Email</th>
								<th>Status</th>
								<th>Created at</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
									@isset($user)
									@foreach($user as $pro)
									<tr>
										<td>@isset($pro->id){{$pro->id}}@endisset</td>
										<td><img src="@isset($pro->images){{asset('images/user/'.$pro->images)}}@else{{asset('images/user/no-image.png')}}@endif" id="profile-img-tag" height="60" width = "60"></td>
										<td>@isset($pro->name){{$pro->name}}@endisset</td>
										<td>@isset($pro->email){{$pro->email}}@endisset</td>
										
										<td>@if($pro->email_verified_at) <span class="btn btn-success">verified</span> @else <span class="btn btn-primary">non verified</span> @endif</td>
										<td>

											@isset($pro->created_at){{$pro->created_at}}@endisset
										</td>
										<td><a href="{{route('user.edit',$pro->id)}}" class="btn btn-info btn-sm">Edit</a></td>
									</tr>
									@endforeach
									@endisset
						</tbody>
					</table>

					{{ $user->links() }}
				</div>
			</div>
		</section>


@endsection

@push('post-styles')
	<link href="{{asset('assets/bootstrap-datatable/css/dataTables.bootstrap4.min.css')}}" rel="stylesheet" type="text/css">
	<link href="{{asset('assets/bootstrap-datatable/css/buttons.bootstrap4.min.css')}}" rel="stylesheet" type="text/css">
@endpush

@push('post-scripts')
<script src="{{asset('assets/bootstrap-datatable/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/buttons.bootstrap4.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/jszip.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/pdfmake.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/vfs_fonts.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/buttons.html5.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/buttons.print.min.js')}}"></script>
<script src="{{asset('assets/bootstrap-datatable/js/buttons.colVis.min.js')}}"></script>

<script>
	$(document).ready(function() {
     //Default data table
     $('#default-datatable').DataTable();


     var table = $('#example').DataTable( {
     	"order": [[ 0, "desc" ]],
     	lengthChange: false,
     	buttons: [ 'copy', 'excel', 'pdf', 'print', 'colvis' ]
     } );

     table.buttons().container()
     .appendTo( '#example_wrapper .col-md-6:eq(0)' );

 } );
</script>
@endpush